<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_barang');
        $this->load->library('form_validation');
        date_default_timezone_set('Asia/Jakarta');
    }

    public function index()
    {
        $barang = $this->M_barang->view();
        $data = array(
            'konten' => 'barang/index',
            'data_barang' => $barang,
        );
        $this->load->view('v_index', $data);
    }

    public function create() 
    {
        $data = array(
            'konten' => 'barang/form',
            'button' => 'Create',
            'action' => site_url('barang/create_action'),
            'kode' => set_value('kode'),
            'nama' => set_value('nama'),
            'harga' => set_value('harga')
	    );
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {            
            $data = array(
                'kode' => $this->input->post('kode'),
                'nama' => $this->input->post('nama'),
                'harga' => $this->input->post('harga')
            );
            $a = $this->M_barang->add(json_encode($data));
            redirect(site_url('barang'));
            //print_r($a);
        }
    }
    
    public function get_by($id) 
    {
        $row = $this->M_barang->getId($id);
        $show = $row->data;
        if ($show) {
            $data = array(
                'konten' => 'barang/form',
                'button' => 'Update',
                'action' => site_url('barang/update_action'),
                'kode' => set_value('kode',$show->kode),
                'nama' => set_value('nama',$show->nama),
                'harga' => set_value('harga',$show->harga)
            );
            $this->load->view('v_index', $data);
        } else {
            redirect(site_url('barang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kode', TRUE));
        } else {
            $data = array(
                'kode' => $this->input->post('kode'),
                'nama' => $this->input->post('nama'),
                'harga' => $this->input->post('harga')
	        );

            $this->M_barang->update($this->input->post('kode', TRUE), json_encode($data));
            redirect(site_url('barang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->M_barang->getId($id);

        if ($row) {
            $this->M_barang->delete($id);
            redirect(site_url('barang'));
        } else {
            redirect(site_url('barang'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kode', 'Kode', 'trim|required');
	$this->form_validation->set_rules('nama', 'Nama', 'trim|required');
	$this->form_validation->set_rules('harga', 'Harga', 'trim|required');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file barang.php */
/* Location: ./application/controllers/barang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-02 11:43:24 */
/* http://harviacode.com */