<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_customer');
        $this->load->library('form_validation');
        date_default_timezone_set('Asia/Jakarta');
    }

    public function index()
    {
        $customer = $this->M_customer->view();
        $data = array(
            'konten' => 'customer/index',
            'data_customer' => $customer,
        );
        $this->load->view('v_index', $data);
    }

    public function create() 
    {
        $data = array(
            'konten' => 'customer/form',
            'button' => 'Create',
            'action' => site_url('customer/create_action'),
            'kode' => set_value('kode'),
            'name' => set_value('name'),
            'telp' => set_value('telp')
	    );
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {            
            $data = array(
                'kode' => $this->input->post('kode'),
                'name' => $this->input->post('name'),
                'telp' => $this->input->post('telp')
            );
            $a = $this->M_customer->add(json_encode($data));
            redirect(site_url('customer'));
            //print_r($a);
        }
    }
    
    public function get_by($id) 
    {
        $row = $this->M_customer->getId($id);
        $show = $row->data;
        if ($show) {
            $data = array(
                'konten' => 'customer/form',
                'button' => 'Update',
                'action' => site_url('customer/update_action'),
                'kode' => set_value('kode',$show->kode),
                'name' => set_value('name',$show->name),
                'telp' => set_value('telp',$show->telp)
            );
            $this->load->view('v_index', $data);
        } else {
            redirect(site_url('customer'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kode', TRUE));
        } else {
            $data = array(
                'kode' => $this->input->post('kode'),
                'name' => $this->input->post('name'),
                'telp' => $this->input->post('telp')
	        );

            $this->M_customer->update($this->input->post('kode', TRUE), json_encode($data));
            redirect(site_url('customer'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->M_customer->getId($id);

        if ($row) {
            $this->M_customer->delete($id);
            redirect(site_url('customer'));
        } else {
            redirect(site_url('customer'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kode', 'Kode', 'trim|required');
	$this->form_validation->set_rules('name', 'Name', 'trim|required');
	$this->form_validation->set_rules('telp', 'Telp', 'trim|required');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file customer.php */
/* Location: ./application/controllers/customer.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-02 11:43:24 */
/* http://harviacode.com */